# Generated by Django 5.2.16 on 2026-10-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation_studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='quality_review',
            field=models.JSONField(default=dict),
        ),
    ]
