"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env") #server/.env 파일의 값을 환경변수로 등록
G2B_API_KEY = os.getenv("G2B_API_KEY")#.evn에서 나라장터 인증키를 가져옴


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Local development defaults; deployments must supply their own secret.
DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() in {"true", "1", "yes"}
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY") or "django-insecure-bid3-local-development-only"
if not DEBUG and not os.getenv("DJANGO_SECRET_KEY"):
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured("DJANGO_SECRET_KEY is required when DJANGO_DEBUG=false.")
ALLOWED_HOSTS = [host.strip() for host in os.getenv(
    "DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1",
).split(",") if host.strip()]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "corsheaders", # Next.js에서 Django API로 보내는 요청을 허용
    "rest_framework", # JSON API와 serializer 기능을 Django에 등록
    "rest_framework.authtoken", # 로그인한 사용자에게 Token을 발급
    "bids.apps.BidsConfig", #입찰 공고 기능을 장고에 등록하는것임
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "OPTIONS": {
            "timeout": 30,  # 자동 수집과 AI 결과 저장이 겹치면 잠금이 풀릴 때까지 기다림
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"  # 나라장터에서 내려받은 첨부파일 저장 위치
PROPOSAL_DEFAULT_TEMPLATE_ID = "public"
PROPOSAL_TEMPLATES = {  # 웹에서 고를 수 있는 제안서 디자인과 실제 파일을 연결
    "corporate": {
        "name": "코퍼레이트 블루",
        "description": "공공기관 제안에 어울리는 안정적인 기본형",
        "path": BASE_DIR / "proposal_templates" / "default.pptx",
        "target_slides": 30,
    },
    "modern": {
        "name": "모던 네이비",
        "description": "비대칭 그리드와 청록 포인트를 활용한 현대적 전문형",
        "path": BASE_DIR / "proposal_templates" / "modern.pptx",
        "target_slides": 30,
    },
    "public": {
        "name": "공공입찰 실무형",
        "description": "요구사항·평가항목·수행체계가 선명한 공공 제안형",
        "path": BASE_DIR / "proposal_templates" / "public_standard.pptx",
        "target_slides": 30,
    },
    "evergreen": {
        "name": "에버그린 그리드",
        "description": "실행 계획과 운영 체계를 차분하게 보여주는 신뢰형",
        "path": BASE_DIR / "proposal_templates" / "evergreen_grid.pptx",
        "target_slides": 30,
    },
    "burgundy": {
        "name": "클래식 버건디",
        "description": "교육·컨설팅 제안에 어울리는 절제된 고급형",
        "path": BASE_DIR / "proposal_templates" / "classic_burgundy.pptx",
        "target_slides": 30,
    },
}
PROPOSAL_DEFAULT_TEMPLATE_PATH = PROPOSAL_TEMPLATES[
    PROPOSAL_DEFAULT_TEMPLATE_ID
]["path"]  # 기존 코드와 테스트에서 사용하는 기본 템플릿 경로

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

TEST_RUNNER = "maintenance.testing.IsolatedRoutingRunner"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ]
}

CORS_ALLOWED_ORIGINS = [origin.strip() for origin in os.getenv(
    "DJANGO_CORS_ALLOWED_ORIGINS", "http://localhost:3000,http://127.0.0.1:3000",
).split(",") if origin.strip()]
