// BID3 original designs. External galleries inform broad design directions only.
// Colors are background / ink / accent / soft surface. All text remains editable.
const definitions = [
  ['civic_navy','시빅 네이비','공공·행정','공공 제안의 근거와 수행 체계를 강조하는 좌측 정렬형','navy','FFFFFF','172C48','2659A6','EDF2F8',0],
  ['policy_paper','폴리시 페이퍼','공공·행정','넓은 여백과 문서형 목차를 갖춘 정책 보고형','editorial','F6F3EC','263342','8C333B','EAE5DA',1],
  ['public_cobalt','퍼블릭 코발트','공공·행정','큰 제목과 선명한 대비로 핵심 제안을 전달하는 발표형','statement','F9FBFF','182C65','254ECC','E8EEFC',2],
  ['municipal_teal','로컬 티얼','공공·행정','지역 사업의 대상과 실행 단계를 분리한 정돈형','sidebar','FAFCFB','173C40','16766E','E5F1EE',3],
  ['civic_mono','시빅 모노','공공·행정','흑백 인쇄와 평가위원의 빠른 읽기에 적합한 실무형','ledger','FFFFFF','24282D','45515E','EEF0F2',4],
  ['learning_sage','러닝 세이지','교육·연구','교육 대상과 프로그램 구성을 차분하게 보여주는 편집형','editorial','F5F6EE','283D35','427354','E8EDDF',5],
  ['academy_burgundy','아카데미 버건디','교육·연구','대칭 표지와 충분한 본문 공간을 갖춘 학술 제안형','centered','FBF7F2','4B2930','8B3D4B','F0E4E4',6],
  ['research_indigo','리서치 인디고','교육·연구','연구 질문과 방법론을 구분해 보여주는 분석형','split','FFFFFF','302B58','5A4BAB','EEEAF8',7],
  ['classroom_apricot','클래스룸 애프리콧','교육·연구','큰 단계 번호와 따뜻한 색으로 읽기 쉬운 교육형','numbered','FFFAF4','49362C','B96330','F9ECDC',8],
  ['seminar_ink','세미나 잉크','교육·연구','간결한 제목과 논리적인 비교 구성을 갖춘 세미나형','minimal','F8F8F7','242B35','315D78','E7EDF0',9],
  ['digital_midnight','디지털 미드나이트','기술·디지털','짙은 표지와 밝은 본문으로 기술 구조를 설명하는 전문형','dark','F7F9FC','182842','436DCE','E8EEF9',10],
  ['data_cyan','데이터 시안','기술·디지털','기술 지표와 검증 근거를 명확히 구분하는 데이터형','ledger','FFFFFF','173840','08788E','E6F3F6',11],
  ['cloud_violet','클라우드 바이올렛','기술·디지털','비대칭 제목과 단계별 실행 내용이 돋보이는 플랫폼형','offset','FAF8FE','352751','7652B0','F0EAF8',12],
  ['product_lime','프로덕트 라임','기술·디지털','강한 표지 대비와 간결한 핵심 문장을 쓰는 제품형','statement','FAFCF5','283C24','4D791F','EBF1DE',13],
  ['system_slate','시스템 슬레이트','기술·디지털','요구사항과 설계 대응을 나란히 비교하는 시스템형','sidebar','F8FAFC','2D3E4F','42677F','E6EDF2',14],
  ['forest_plan','포레스트 플랜','환경·시설','사업 범위와 현장 운영 계획을 연결하는 환경 제안형','dark','F8FAF6','223E30','447A46','E6EFE2',15],
  ['terra_field','테라 필드','환경·시설','현장 조사와 실행 계획을 넓은 지면에 담는 기록형','editorial','FAF5EB','4B3E2C','A2682E','F0E5D2',16],
  ['ocean_blue','오션 블루','환경·시설','명료한 대칭 구성으로 지속가능 사업을 설명하는 발표형','centered','F6FBFC','174150','127A96','DFF0F4',17],
  ['energy_olive','에너지 올리브','환경·시설','목표와 점검 기준을 전면에 배치한 에너지 기획형','numbered','F9F9F0','3A4326','6B782D','ECEFD9',18],
  ['urban_concrete','어반 콘크리트','환경·시설','시설·건축 사업의 공정과 책임을 정리하는 정밀형','split','FAF9F7','353738','7B6252','EEE8E2',19],
  ['strategy_charcoal','스트래티지 차콜','경영·컨설팅','큰 요약문과 세부 근거를 분리한 전략 제안형','dark','FAFAF8','26272A','756343','ECE9E0',20],
  ['executive_wine','이그제큐티브 와인','경영·컨설팅','절제된 타이포그래피와 비교 중심의 경영 보고형','offset','FCF8F7','472C37','8B385D','F2E7ED',21],
  ['business_sand','비즈니스 샌드','경영·컨설팅','분석부터 실행까지 흐름이 읽히는 밝은 컨설팅형','minimal','F8F5EF','423A31','947047','EEE5D6',22],
  ['supply_steel','서플라이 스틸','경영·컨설팅','물품 사양과 납품·검수 계획에 어울리는 정돈형','ledger','FFFFFF','243E55','32688D','EAF1F6',23],
  ['venture_coral','벤처 코럴','경영·컨설팅','고객 문제와 제안 가치를 크게 제시하는 피치형','statement','FFFAF7','4E302B','B6503C','F8E6DF',24],
  ['culture_plum','컬처 플럼','문화·홍보','여백과 비대칭 제목으로 문화 사업의 인상을 만드는 제안형','split','FCF8FC','4B2F50','914B8D','F2E6F0',25],
  ['tourism_moss','투어리즘 모스','문화·홍보','지역 자원과 운영 계획을 차분하게 담는 관광 기획형','sidebar','F6F7F0','364333','657A48','E9EDDE',26],
  ['campaign_tangerine','캠페인 탠저린','문화·홍보','크고 명확한 제목과 메시지 중심의 홍보 제안형','numbered','FFF9F3','503828','B85E25','F7E8D8',27],
  ['community_lavender','커뮤니티 라벤더','문화·홍보','이해관계자와 참여 과정을 부드럽게 설명하는 협력형','centered','FAF9FE','3C3553','7660A1','EEEBF7',28],
  ['studio_ruby','스튜디오 루비','문화·홍보','강한 제목 대비와 편집 지면 구성을 갖춘 크리에이티브형','offset','FFFAF9','502D35','A93C53','F6E6EA',29],
];

export const catalog = definitions.map(([id,name,category,description,composition,bg,ink,accent,soft,variant]) => ({
  id, name, category, description, composition, variant,
  palette:{bg:`#${bg}`,ink:`#${ink}`,accent:`#${accent}`,soft:`#${soft}`},
  tags:[category, ({editorial:'문서형',centered:'대칭형',split:'분할형',numbered:'단계형',minimal:'미니멀',dark:'다크 표지',ledger:'표 중심',offset:'비대칭',sidebar:'좌측 목차',statement:'발표형',navy:'공공 제안형'})[composition]],
  slide_count:20, target_slides:20, collection:'BID3 스튜디오', origin:'original',
  license_note:'BID3 자체 제작 · 외부 서비스의 템플릿이나 이미지가 포함되지 않습니다.',
  file:`${id}.pptx`,
}));

export const pages = [
  {role:'cover',title:'사업 제안서',kind:'cover',labels:['사업명 확인 필요','발주기관 확인 필요','제안사 확인 필요 · 제출일 확인 필요']},
  {role:'contents',title:'제안의 구성',kind:'contents',labels:['사업 이해와 제안 방향','수행 방법과 운영 체계','품질·위험·보안 관리','검증 근거와 성과 관리']},
  {role:'summary',title:'제안 요약',kind:'summary',labels:['사업의 목적','주요 수행 내용','완료 기준']},
  {role:'problem',title:'사업 이해와 핵심 과제',kind:'comparison',labels:['발주처의 현황','해결해야 할 과제']},
  {role:'objective',title:'사업 목표와 적용 범위',kind:'columns',labels:['대상과 범위','정량 목표','적용 조건']},
  {role:'compliance',title:'요구사항 대응 계획',kind:'table',headers:['요구사항','수행 방안','확인 근거'],rows:4},
  {role:'evaluation',title:'평가항목별 제안 근거',kind:'table',headers:['평가항목','제안 내용','증빙·관련 페이지'],rows:4},
  {role:'strategy',title:'핵심 수행 전략',kind:'columns',labels:['접근 방법','수행의 차별점','실행 조건']},
  {role:'process',title:'단계별 수행 절차',kind:'process',labels:['착수·요건 확인','설계·준비','실행·점검','검증·인계']},
  {role:'domain',title:'세부 과업 수행 방안',kind:'comparison',labels:['주요 과업','수행 방법과 산출물']},
  {role:'timeline',title:'추진 일정과 마일스톤',kind:'table',headers:['단계','기간','주요 활동','완료 기준'],rows:4},
  {role:'organization',title:'수행 조직과 역할',kind:'table',headers:['역할','담당·투입 조건','책임과 수행 내용'],rows:4},
  {role:'governance',title:'보고와 의사결정',kind:'process',labels:['진행 현황 보고','쟁점 검토','발주처 협의','변경사항 반영']},
  {role:'quality',title:'품질관리와 검수',kind:'columns',labels:['품질 기준','검증 방법','보완과 재검수']},
  {role:'risk',title:'위험과 대응 계획',kind:'table',headers:['위험 요인','예방·대응 방안','담당·점검 기준'],rows:4},
  {role:'security',title:'정보보호와 준수사항',kind:'comparison',labels:['보호 대상과 준수 기준','통제 방법과 점검 기록']},
  {role:'metrics',title:'성과지표와 측정 방법',kind:'table',headers:['성과지표','목표·근거','측정 방법·주기'],rows:4},
  {role:'evidence',title:'수행 역량과 검증 자료',kind:'comparison',labels:['관련 역량과 수행 경험','확인 가능한 증빙']},
  {role:'outcomes',title:'산출물과 완료 기준',kind:'table',headers:['주요 산출물','제출·인계 방법','완료 기준'],rows:4},
  {role:'closing',title:'제안의 핵심',kind:'closing',labels:['수행 범위 확인 필요','실행 원칙 확인 필요','협의 사항 확인 필요']},
];
