# Generated by Django 5.2.16 on 2026-07-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_ntce_no', models.CharField(max_length=50)),
                ('bid_ntce_ord', models.CharField(default='000', max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('business_type', models.CharField(blank=True, max_length=50)),
                ('contract_method', models.CharField(blank=True, max_length=100)),
                ('notice_organization', models.CharField(blank=True, max_length=200)),
                ('demand_organization', models.CharField(blank=True, max_length=200)),
                ('notice_date', models.DateField(blank=True, null=True)),
                ('close_at', models.DateTimeField(blank=True, null=True)),
                ('budget_amount', models.BigIntegerField(blank=True, null=True)),
                ('estimated_price', models.BigIntegerField(blank=True, null=True)),
                ('region_limit', models.BooleanField(default=False)),
                ('allowed_region', models.TextField(blank=True)),
                ('industry_limit', models.BooleanField(default=False)),
                ('allowed_industry', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bid_ntce_no', 'bid_ntce_ord'), name='unique_bid_notice')],
            },
        ),
    ]
