# Generated by Django 5.2.16 on 2026-07-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidnotice',
            name='deadline_status',
            field=models.CharField(choices=[('active', '유효'), ('expired', '마감'), ('review', '확인 필요')], default='review', max_length=20),
        ),
    ]
