# Generated by Django 5.2.16 on 2026-07-13 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0002_bidnotice_deadline_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                (
                    "business_registration_number",
                    models.CharField(max_length=20, unique=True),
                ),
                ("representative_name", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("established_date", models.DateField(blank=True, null=True)),
                ("address", models.TextField()),
                ("industry", models.CharField(max_length=200)),
                (
                    "company_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("small-medium", "중소기업"),
                            ("small", "소기업"),
                            ("micro", "소상공인"),
                            ("other", "기타"),
                        ],
                        max_length=20,
                    ),
                ),
                ("employee_count", models.PositiveIntegerField(blank=True, null=True)),
                ("capital", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "annual_revenue",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("main_business", models.TextField()),
                ("capabilities", models.TextField(blank=True)),
                ("licenses", models.TextField(blank=True)),
                ("past_performance", models.TextField(blank=True)),
                ("preferred_keywords", models.TextField()),
                (
                    "preferred_bid_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("service", "용역"),
                            ("goods", "물품"),
                            ("construction", "공사"),
                        ],
                        max_length=20,
                    ),
                ),
                ("preferred_region", models.CharField(blank=True, max_length=200)),
                (
                    "min_bid_amount",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "max_bid_amount",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
