# Generated by Django 5.2.16 on 2026-07-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0005_bidanalysis_recommendedbid"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendedbid",
            name="is_match",
            field=models.BooleanField(default=True),
        ),
    ]
