# Generated by Django 5.2.16 on 2026-07-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0006_recommendedbid_is_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="excluded_keywords",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="required_keywords",
            field=models.TextField(blank=True),
        ),
    ]
