# Generated by Django 5.2.16 on 2026-07-25

import bids.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0010_companydocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="BidProposal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("output_format", models.CharField(choices=[("docx", "Word"), ("pptx", "PowerPoint")], max_length=10)),
                ("template_mode", models.CharField(default="new_document", max_length=30)),
                ("strategy", models.JSONField(default=dict)),
                ("draft", models.JSONField(default=dict)),
                ("generated_file", models.FileField(upload_to=bids.models.bid_proposal_upload_path)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "saved_bid",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposal",
                        to="bids.savedbid",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_proposals",
                        to="bids.companydocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
