# Generated by Django 5.2.16 on 2026-07-29 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0013_rename_bidproposal_draft"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyKnowledgeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("company_overview", "회사 개요"),
                            ("history", "연혁"),
                            ("personnel", "인력"),
                            ("infrastructure", "인프라"),
                            ("capability", "기술·역량"),
                            ("performance", "수행 실적"),
                            ("methodology", "수행 방법론"),
                            ("strength", "강점·차별점"),
                            ("certification", "면허·인증"),
                            ("other", "기타"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("source_locations", models.JSONField(blank=True, default=list)),
                ("evidence_excerpt", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "검토 대기"),
                            ("approved", "승인"),
                            ("rejected", "제외"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_items",
                        to="bids.companydocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_knowledge_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("category", "title"),
                "indexes": [
                    models.Index(
                        fields=["user", "review_status"],
                        name="company_know_user_status",
                    ),
                    models.Index(
                        fields=["source_document", "category"],
                        name="company_know_doc_category",
                    ),
                ],
            },
        ),
    ]
