# Generated by Django 5.2.16 on 2026-07-29 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0014_companyknowledgeitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="companyknowledgeitem",
            name="company_know_user_status",
        ),
        migrations.RemoveField(
            model_name="bidproposal",
            name="source_document",
        ),
        migrations.RemoveField(
            model_name="companyknowledgeitem",
            name="review_status",
        ),
        migrations.AlterField(
            model_name="bidproposal",
            name="template_mode",
            field=models.CharField(default="default_template", max_length=30),
        ),
        migrations.AddIndex(
            model_name="companyknowledgeitem",
            index=models.Index(
                fields=["user", "category"], name="company_know_user_category"
            ),
        ),
    ]
