# Generated by Django 5.2.16 on 2026-07-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0015_remove_companyknowledgeitem_company_know_user_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companydocument",
            name="target_company",
        ),
    ]
