# Generated by Django 5.2.16 on 2026-08-22 07:05

import bids.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0021_companyprofile_website_urls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectReferenceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=bids.models.project_reference_upload_path
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("extracted_knowledge", models.JSONField(blank=True, default=list)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-uploaded_at",),
            },
        ),
        migrations.AddField(
            model_name="savedbid",
            name="proposal_trashed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyknowledgeitem",
            name="source_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge_items",
                to="bids.companydocument",
            ),
        ),
        migrations.CreateModel(
            name="CompanyWebsitePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=1000)),
                ("title", models.CharField(blank=True, max_length=300)),
                ("extracted_text", models.TextField()),
                ("content_hash", models.CharField(max_length=64)),
                ("collected_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_website_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("url",),
            },
        ),
        migrations.AddField(
            model_name="companyknowledgeitem",
            name="source_website_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge_items",
                to="bids.companywebsitepage",
            ),
        ),
        migrations.AddIndex(
            model_name="companyknowledgeitem",
            index=models.Index(
                fields=["source_website_page", "category"],
                name="company_know_web_category",
            ),
        ),
        migrations.AddField(
            model_name="projectreferencedocument",
            name="saved_bid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reference_documents",
                to="bids.savedbid",
            ),
        ),
        migrations.AddConstraint(
            model_name="companywebsitepage",
            constraint=models.UniqueConstraint(
                fields=("user", "url"), name="unique_user_company_website_page"
            ),
        ),
    ]
