# Generated by Django 5.2.16 on 2026-10-09 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0022_projectreferencedocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companyknowledgeitem',
            name='review_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='companyknowledgeitem',
            name='review_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='companyknowledgeitem',
            name='review_status',
            field=models.CharField(choices=[('pending', '검토 대기'), ('approved', '검토 완료'), ('excluded', '사용 제외')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='companyknowledgeitem',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyknowledgeitem',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_company_knowledge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyknowledgeitem',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='document_type',
            field=models.CharField(choices=[('proposal', '제안서'), ('company_introduction', '회사소개서'), ('evidence', '회사 증빙')], max_length=30),
        ),
    ]
