# Generated by Django 5.2.16 on 2026-10-09 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0023_company_evidence_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('generate', '생성'), ('review', '전체 검수')], max_length=20)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('worker_pid', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saved_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_tasks', to='bids.savedbid')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('saved_bid',), name='bid_one_active_proposal_task')],
            },
        ),
    ]
